# Generated by Django 4.2.10 on 2024-04-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_room_amenity_room_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenity',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenity',
            field=models.ManyToManyField(related_name='rooms', to='reservations.amenity'),
        ),
    ]
